id: 5fbedbee5d9f4cfa83a51aee51d94cc7
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_285-The_Dedication_Fulfilling_All_Aspirations-v2
  language: bo
  author: ''
  volume: {}
